default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: find-your-fresh_development

test:
  <<: *default
  database: find-your-fresh_test

production:
  <<: *default
  database: find-your-fresh_production
